DEFINE VARIABLE lcICC AS CHARACTER NO-UNDO. 
DEFINE VARIABLE i AS INT64 NO-UNDO. 
DEF STREAM sout.
OUTPUT STREAM sout to /apps/snet/200809/as_ycm912.output.

DO i = 8934040508010534648 to 8934040508010574610:   
   lcICC = STRING(i). 
    
   FIND FIRST SIM WHERE ICC = lcICC NO-LOCK NO-ERROR.
   
   IF AVAIL SIM and SIM.Stock = "MNP" AND SIM.SimStat EQ 1 THEN DO:
      PUT STREAM sout UNFORMATTED SIM.ICC " " SIM.Stock " -> NEW " SIM.SimStat SKIP.
      FIND CURRENT SIM EXCLUSIVE-LOCK NO-ERROR.
      SIM.Stock = "NEW".
   END.
   ELSE  DO:
      IF AVAIL SIM THEN 
      PUT STREAM sout UNFORMATTED SIM.ICC " " SIM.Stock " " SIM.SimStat " SKIPPED" SKIP.
   END.   
END.  

output stream sout close.
