#
b /db1/counter/bifo/counter.b1
#
d "Schema Area":6,32;1 /db1/counter/data/counter.d1
#
d "Sta_Data_256":7,256;64 /db1/counter/data/counter_7.d1
#
d "Sta_Data_128":8,128;64 /db1/counter/data/counter_8.d1
#
d "Sta_Data_64":9,64;64 /db1/counter/data/counter_9.d1
#
d "Dyn_Data_64":10,64;64 /db1/counter/data/counter_10.d1
#
d "Sta_Index_1":11,1;64 /db1/counter/index/counter_11.d1
#
d "Sta_Index_2":12,1;1 /db1/counter/index/counter_12.d1
#
d "Dyn_Index_1":13,1;64 /db1/counter/index/counter_13.d1
#
d "Dyn_Index_2":14,64;8 /db1/counter/data/counter_14.d1
