#
b /db1/fraudcdr/bifo/fraudcdr.b1 v 2048000
#
d "Schema Area":6,64;1 /db1/fraudcdr/data/fraudcdr.d1
#
d "Dyn_Data_64":7,64;8 /db1/fraudcdr/data/fraudcdr_7.d1
#
d "Dyn_Index1":8,1;8 /db1/fraudcdr/index/fraudcdr_8.d1
#
d "Dyn_Index2":9,1;8 /db1/fraudcdr/index/fraudcdr_9.d1
#
d "Dyn_Index3":10,1;8 /db1/fraudcdr/index/fraudcdr_10.d1
#
d "Dyn_Index4":11,1;8 /db1/fraudcdr/index/fraudcdr_11.d1
#
d "Dyn_Index5":12,1;8 /db1/fraudcdr/index/fraudcdr_12.d1
#
d "Dyn_Index6":13,1;8 /db1/fraudcdr/index/fraudcdr_13.d1
#
d "Dtl_Data_64":14,64;8 /db1/fraudcdr/data/fraudcdr_14.d1
#
d "Dtl_Index2":15,1;8 /db1/fraudcdr/index/fraudcdr_15.d1
