#
b /db1/mobile/bifo/mobile.b1 v 2048000
#
d "Schema Area":6,32;1 /db1/mobile/data/mobile.d1
#
d "Sta_Data_256":7,256;1 /db1/mobile/data/mobile_7.d1 v 2048000
#
d "Sta_Data_64":8,64;8 /db1/mobile/data/mobile_8.d1 v 2048000
#
d "Sta_Data_32":9,32;64 /db1/mobile/data/mobile_9.d1 v 2048000
#
d "Sta_Index_1":10,1;512 /db1/mobile/index/mobile_10.d1 v 2048000
#
d "Sta_Index_2":11,1;64 /db1/mobile/index/mobile_11.d1 v 2048000
#
d "Sta_Index_3":12,1;8 /db1/mobile/index/mobile_12.d1 v 2048000
#
d "Sta_Data_128":13,128;1 /db1/mobile/data/mobile_13.d1 v 2048000
#
a /db1/mobile/aifo/mobile.a1 v 2048000
#
a /db1/mobile/aifo/mobile.a2 v 2048000
#
a /db1/mobile/aifo/mobile.a3 v 2048000
#
a /db1/mobile/aifo/mobile.a4 v 2048000
#
d "CDF_Data":90,128;512 /db1/mobile/data/mobile_90.d1 v 2048000
#
d "CDF_Index":91,1;64 /db1/mobile/index/mobile_91.d1 v 2048000
