#
b /db1/ordercanal/bifo/ordercanal.b1 v 2048000
#
d "Schema Area":6,32;1 /db1/ordercanal/data/ordercanal.d1
#
d "Sta_Data_256":7,256;1 /db1/ordercanal/data/ordercanal_7.d1 v 2048000
#
d "Sta_Data_128":8,128;8 /db1/ordercanal/data/ordercanal_8.d1 v 2048000
#
d "Sta_Data_64":9,64;64 /db1/ordercanal/data/ordercanal_9.d1 v 2048000
#
d "Sta_Data_32":10,32;512 /db1/ordercanal/data/ordercanal_10.d1 v 2048000
#
d "Dyn_Data_256":11,256;1 /db1/ordercanal/data/ordercanal_11.d1 v 2048000
#
d "Dyn_Data_128":12,128;8 /db1/ordercanal/data/ordercanal_12.d1 v 2048000
#
d "Dyn_Data_32":13,32;512 /db1/ordercanal/data/ordercanal_13.d1 v 2048000
#
d "Sta_Index_1":14,1;64 /db1/ordercanal/index/ordercanal_14.d1 v 2048000
#
d "Sta_Index_2":15,1;1 /db1/ordercanal/index/ordercanal_15.d1 v 2048000
#
d "Dyn_Index_1":16,1;64 /db1/ordercanal/index/ordercanal_16.d1 v 2048000
#
a /db1/ordercanal/aifo/ordercanal.a1 v 2048000
#
a /db1/ordercanal/aifo/ordercanal.a2 v 2048000
#
a /db1/ordercanal/aifo/ordercanal.a3 v 2048000
#
a /db1/ordercanal/aifo/ordercanal.a4 v 2048000
#
d "CDF_Data":90,128;512 /db1/ordercanal/data/ordercanal_90.d1 v 2048000
#
d "CDF_Index":91,1;64 /db1/ordercanal/index/ordercanal_91.d1 v 2048000
