#
b /db1/prepcdr/bifo/prepcdr.b1 v 2048000
#
d "Schema Area":6,32;1 /db1/prepcdr/data/prepcdr.d1
#
d "Dyn_Data_64":7,64;512 /db1/prepcdr/data/prepcdr_7.d1 v 2048000
#
d "Dyn_Index1":8,1;8 /db1/prepcdr/index/prepcdr_8.d1 v 2048000
#
d "Dyn_Index2":9,1;8 /db1/prepcdr/index/prepcdr_9.d1 v 2048000
#
d "Dyn_Index3":10,1;8 /db1/prepcdr/index/prepcdr_10.d1 v 2048000
#
d "Dyn_Index4":11,1;8 /db1/prepcdr/index/prepcdr_11.d1 v 2048000
#
d "Dyn_Index5":12,1;8 /db1/prepcdr/index/prepcdr_12.d1 v 2048000
#
d "Dyn_Index6":13,1;8 /db1/prepcdr/index/prepcdr_13.d1 v 2048000
#
d "Dyn_Index7":14,1;8 /db1/prepcdr/index/prepcdr_14.d1 v 2048000
#
d "Dyn_Index8":15,1;8 /db1/prepcdr/index/prepcdr_15.d1 v 2048000
#
a /db1/prepcdr/aifo/prepcdr.a1 v 2048000
#
a /db1/prepcdr/aifo/prepcdr.a2 v 2048000
#
a /db1/prepcdr/aifo/prepcdr.a3 v 2048000
#
a /db1/prepcdr/aifo/prepcdr.a4 v 2048000
