#
b /db1/prepedr/bifo/prepedr.b1
#
d "Schema Area":6,32;1 /db1/prepedr/data/prepedr.d1
#
d "Dyn_Data_64":7,64;8 /db1/prepedr/data/prepedr_7.d1
#
d "Dyn_Index1":8,1;8 /db1/prepedr/index/prepedr_8.d1
#
d "Dyn_Index2":9,1;8 /db1/prepedr/index/prepedr_9.d1
#
d "Dyn_Index3":10,1;8 /db1/prepedr/index/prepedr_10.d1
#
d "Dyn_Index4":11,1;8 /db1/prepedr/index/prepedr_11.d1
#
d "Dtl_Data_64":12,64;8 /db1/prepedr/data/prepedr_12.d1
#
d "Dtl_Index1":13,1;8 /db1/prepedr/index/prepedr_13.d1
