#
b /db1/reratelog/bifo/reratelog.b1 v 2048000
#
d "Schema Area":6,64;1 /db1/reratelog/data/reratelog.d1
#
d "Sta_Data_64":7,64;64 /db1/reratelog/data/reratelog_7.d1 v 2048000
#
d "Sta_Data_128":8,128;64 /db1/reratelog/data/reratelog_8.d1 v 2048000
#
d "Sta_Index_1":9,1;64 /db1/reratelog/index/reratelog_9.d1 v 2048000
#
d "Sta_Index_2":10,1;64 /db1/reratelog/index/reratelog_10.d1 v 2048000
#
d "Sta_Index_3":11,1;64 /db1/reratelog/index/reratelog_11.d1 v 2048000
#
a /db1/reratelog/aifo/reratelog.a1 v 2048000
#
a /db1/reratelog/aifo/reratelog.a2 v 2048000
#
a /db1/reratelog/aifo/reratelog.a3 v 2048000
#
a /db1/reratelog/aifo/reratelog.a4 v 2048000
