mkdir /store/riftp/logistics/masmovil
mkdir /store/riftp/logistics/masmovil/incoming
mkdir /store/riftp/logistics/masmovil/incoming/incoming
mkdir /store/riftp/logistics/masmovil/incoming/spool
mkdir /store/riftp/logistics/masmovil/incoming/processed
mkdir /store/riftp/logistics/masmovil/outgoing
mkdir /store/riftp/logistics/masmovil/outgoing/outgoing
mkdir /store/riftp/logistics/masmovil/outgoing/spool
mkdir /store/riftp/logistics/masmovil/outgoing/processed
