DEF VAR gcExpectedAccount            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedAddress            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedBrand              AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCampaign           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCampaignCode       AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCCReference        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedChannel            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCity               AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCLI                AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCLIType            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCompany            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCompanyId          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCoName             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedContractID         AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCountry            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCreUser            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCurrOper           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCustID             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCustIDType         AS CHARACTER NO-UNDO.
DEF VAR gcExpectedCustTitle          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedDeviceID           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedDeviceModel        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedEmail              AS CHARACTER NO-UNDO.
DEF VAR gcExpectedFAT                AS CHARACTER NO-UNDO.
DEF VAR gcExpectedFeeModel           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedFirstName          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedFixedNumber        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedFName              AS CHARACTER NO-UNDO.
DEF VAR gcExpectedHostTable          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedICC                AS CHARACTER NO-UNDO.
DEF VAR gcExpectedIdType             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedIMEI               AS CHARACTER NO-UNDO.
DEF VAR gcExpectedKeyValue           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedLanguage           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedLName              AS CHARACTER NO-UNDO.
DEF VAR gcExpectedLName2             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedMemo               AS CHARACTER NO-UNDO.
DEF VAR gcExpectedMemoText           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedMemoTitle          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedMobileNumber       AS CHARACTER NO-UNDO.
DEF VAR gcExpectedNationality        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedNumberType         AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOldBillingOperator AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOldICC             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOldOperator        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOrderer            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOrdererID          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOrdererIp          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOrderID            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedOrderIDType        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedPaymentMethod      AS CHARACTER NO-UNDO.
DEF VAR gcExpectedPaymentReference   AS CHARACTER NO-UNDO.
DEF VAR gcExpectedPersonId           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedPhoneNumber        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedPostOffice         AS CHARACTER NO-UNDO.
DEF VAR gcExpectedProductCode        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedRegion             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSalesman           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedServiceList        AS CHARACTER NO-UNDO.
DEF VAR gcExpectedServiceNameList    AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSiteName           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSMSNumber          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSource             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedStatusCode         AS CHARACTER NO-UNDO.
DEF VAR gcExpectedStreet             AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSubscriptionType   AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSurName            AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSurName1           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedSurName2           AS CHARACTER NO-UNDO.
DEF VAR gcExpectedTitle              AS CHARACTER NO-UNDO.
DEF VAR gcExpectedUserFName          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedUserLName          AS CHARACTER NO-UNDO.
DEF VAR gcExpectedUserLName2         AS CHARACTER NO-UNDO.
DEF VAR gcExpectedZIP                AS CHARACTER NO-UNDO.
DEF VAR gcExpectedZipCode            AS CHARACTER NO-UNDO.
DEF VAR gdaExpectedBirthDate         AS DATE NO-UNDO.
DEF VAR gdaExpectedBirthDay          AS DATE NO-UNDO.
DEF VAR gdeExpectedAmount            AS DECIMAL NO-UNDO.
DEF VAR gdeExpectedCreStamp          AS DECIMAL NO-UNDO.
DEF VAR gdeExpectedDevicePrice       AS DECIMAL NO-UNDO.
DEF VAR gdeExpectedDiscount          AS DECIMAL NO-UNDO.
DEF VAR gdeExpectedFat               AS DECIMAL NO-UNDO.
DEF VAR gdeExpectedTimeStamp         AS DECIMAL NO-UNDO.
DEF VAR gdeExpectedTopup             AS DECIMAL NO-UNDO.
DEF VAR giExpectedInvCustTole        AS INTEGER NO-UNDO.
DEF VAR giExpectedMemoSeq            AS INTEGER NO-UNDO.
DEF VAR giExpectedMethod             AS INTEGER NO-UNDO.
DEF VAR giExpectedMnpStatus          AS INTEGER NO-UNDO.
DEF VAR giExpectedMsSeq              AS INTEGER NO-UNDO.
DEF VAR giExpectedOrderID            AS INTEGER NO-UNDO.
DEF VAR giExpectedRowType            AS INTEGER NO-UNDO.
DEF VAR giExpectedUserCode           AS INTEGER NO-UNDO.
DEF VAR glExpectedCheck              AS LOGICAL NO-UNDO.
DEF VAR glExpectedEmail3rd           AS LOGICAL NO-UNDO.
DEF VAR glExpectedMarkEmail          AS LOGICAL NO-UNDO.
DEF VAR glExpectedMarkPost           AS LOGICAL NO-UNDO.
DEF VAR glExpectedMarkSMS            AS LOGICAL NO-UNDO.
DEF VAR glExpectedMnpProcessBypass   AS LOGICAL NO-UNDO.
DEF VAR glExpectedNetworkBypass      AS LOGICAL NO-UNDO.
DEF VAR glExpectedNoCharge           AS LOGICAL NO-UNDO.
DEF VAR glExpectedOldPayType         AS LOGICAL NO-UNDO.
DEF VAR glExpectedOperAllMarketing   AS LOGICAL NO-UNDO.
DEF VAR glExpectedOperEmailMarketing AS LOGICAL NO-UNDO.
DEF VAR glExpectedOperPostMarketing  AS LOGICAL NO-UNDO.
DEF VAR glExpectedOperSMSMarketing   AS LOGICAL NO-UNDO.
DEF VAR glExpectedOutEmailMarketing  AS LOGICAL NO-UNDO.
DEF VAR glExpectedOutPostMarketing   AS LOGICAL NO-UNDO.
DEF VAR glExpectedOutSMSMarketing    AS LOGICAL NO-UNDO.
DEF VAR glExpectedPayType            AS LOGICAL NO-UNDO.
DEF VAR glExpectedPost3rd            AS LOGICAL NO-UNDO.
DEF VAR glExpectedSMS3rd             AS LOGICAL NO-UNDO.
