add_datetime( gcAddressStruct,"birthday"            ,DATETIME( gdaExpectedAddressBirthDay ,0 )).
add_string(   gcAddressStruct,"city"                ,gcExpectedAddressCity).
add_string(   gcAddressStruct,"coname"              ,gcExpectedAddressConame).
add_string(   gcAddressStruct,"contact_name"        ,gcExpectedAddressContactName).
add_string(   gcAddressStruct,"country"             ,gcExpectedAddressCountry).
add_string(   gcAddressStruct,"customer_name"       ,gcExpectedAddressCustomerName).
add_string(   gcAddressStruct,"email"               ,gcExpectedAddressEmail).
add_string(   gcAddressStruct,"fname"               ,gcExpectedAddressFName).
add_int(      gcAddressStruct,"language"            ,giExpectedAddressLanguage).
add_string(   gcAddressStruct,"lname"               ,gcExpectedAddressLName).
add_string(   gcAddressStruct,"lname2"              ,gcExpectedAddressLName2).
add_boolean(  gcAddressStruct,"mark_email"          ,glExpectedAddressMarkEmail).
add_boolean(  gcAddressStruct,"mark_email_3rd"      ,glExpectedAddressMarkEmail3rd).
add_boolean(  gcAddressStruct,"mark_post"           ,glExpectedAddressMarkPost).
add_boolean(  gcAddressStruct,"mark_post_3rd"       ,glExpectedAddressMarkPost3rd).
add_boolean(  gcAddressStruct,"mark_sms"            ,glExpectedAddressMarkSMS).
add_boolean(  gcAddressStruct,"mark_sms_3rd"        ,glExpectedAddressMarkSMS3rd).
add_string(   gcAddressStruct,"nationality"         ,gcExpectedAddressNationality).
add_string(   gcAddressStruct,"phone_number"        ,gcExpectedAddressPhoneNumber).
add_string(   gcAddressStruct,"region"              ,gcExpectedAddressRegion).
add_string(   gcAddressStruct,"site_name"           ,gcExpectedAddressSiteName).
add_string(   gcAddressStruct,"sms_number"          ,gcExpectedAddressSmsNumber).
add_string(   gcAddressStruct,"street"              ,gcExpectedAddressStreet).
add_string(   gcAddressStruct,"title"               ,gcExpectedAddressTitle).
add_string(   gcAddressStruct,"zip"                 ,gcExpectedAddressZip).

add_datetime( gcCustomerStruct,"birthday"            ,DATETIME( gdaExpectedBirthDay ,0 )).
add_string(   gcCustomerStruct,"city"                ,gcExpectedPostOffice).
add_string(   gcCustomerStruct,"CodC"                ,gcExpectedCodC).
add_string(   gcCustomerStruct,"CodP"                ,gcExpectedCodP).
add_string(   gcCustomerStruct,"coname"              ,gcExpectedCoName).
add_string(   gcCustomerStruct,"contact_name"        ,gcExpectedOrderer).
add_string(   gcCustomerStruct,"country"             ,gcExpectedCountry).
add_string(   gcCustomerStruct,"email"               ,gcExpectedEmail).
add_string(   gcCustomerStruct,"fname"               ,gcExpectedFName).
add_string(   gcCustomerStruct,"language"            ,gcExpectedParamLanguage).
add_string(   gcCustomerStruct,"lName"               ,gcExpectedLName).
add_string(   gcCustomerStruct,"lName2"              ,gcExpectedLName2).
add_boolean(  gcCustomerStruct,"mark_email"          ,glExpectedMarkEmail).
add_boolean(  gcCustomerStruct,"mark_email_3rd"      ,glExpectedMarkEmail3rd).
add_boolean(  gcCustomerStruct,"mark_post"           ,glExpectedMarkPost).
add_boolean(  gcCustomerStruct,"mark_post_3rd"       ,glExpectedMarkPost3rd).
add_boolean(  gcCustomerStruct,"mark_sms"            ,glExpectedMarkSMS).
add_boolean(  gcCustomerStruct,"mark_sms_3rd"        ,glExpectedMarkSMS3rd).
add_string(   gcCustomerStruct,"nationality"         ,gcExpectedNationality).
add_string(   gcCustomerStruct,"phone_number"        ,gcExpectedFixedNumber).
add_string(   gcCustomerStruct,"region"              ,gcExpectedRegion).
add_string(   gcCustomerStruct,"site_name"           ,gcExpectedCompany).
add_string(   gcCustomerStruct,"sms_number"          ,gcExpectedSMSNumber).
add_string(   gcCustomerStruct,"street"              ,gcExpectedAddress).
add_string(   gcCustomerStruct,"title"               ,gcExpectedTitle).
add_string(   gcCustomerStruct,"zip"                 ,gcExpectedZipCode).

add_string(   gcDeviceStruct,"device_model"        ,gcExpectedParamDeviceModel).
add_double(   gcDeviceStruct,"device_price"        ,gdeExpectedParamDevicePrice).
add_double(   gcDeviceStruct,"discount"            ,gdeExpectedDiscount).
add_string(   gcDeviceStruct,"IMEI"                ,gcExpectedParamIMEI).

add_string(   gcExpectedAddressStruct,"CodC"                ,gcExpectedAddressCodC).
add_string(   gcExpectedAddressStruct,"CodP"                ,gcExpectedAddressCodP).

add_string(   gcOrderStruct,"billing_data"        ,gcExpectedAccount).
add_string(   gcOrderStruct,"campaign_code"       ,gcExpectedCampaign).
add_string(   gcOrderStruct,"channel"             ,gcExpectedParamChannel).
add_boolean(  gcOrderStruct,"check"               ,glExpectedCheck).
add_string(   gcOrderStruct,"CLI"                 ,gcExpectedCLI).
add_string(   gcOrderStruct,"company_id"          ,gcExpectedCompanyId).
add_string(   gcOrderStruct,"contractid"          ,gcExpectedContractID).
add_double(   gcOrderStruct,"fat"                 ,gdeExpectedFAT).
add_string(   gcOrderStruct,"ICC"                 ,gcExpectedICC).
add_string(   gcOrderStruct,"id_type"             ,gcExpectedParamIdType).
add_string(   gcOrderStruct,"memo"                ,gcExpectedMemoText).
add_boolean(  gcOrderStruct,"mnp_process_bypass"  ,glExpectedMnpProcessBypass).
add_boolean(  gcOrderStruct,"network_bypass"      ,glExpectedNetworkBypass).
add_boolean(  gcOrderStruct,"no_charge"           ,glExpectedNoCharge).
add_string(   gcOrderStruct,"number_type"         ,gcExpectedNumberType).
add_string(   gcOrderStruct,"old_billing_category",gcExpectedOldBillCategory).
add_string(   gcOrderStruct,"old_icc"             ,gcExpectedOldICC).
add_string(   gcOrderStruct,"old_operator"        ,gcExpectedCurrOper).
add_string(   gcOrderStruct,"orderer_ip"          ,gcExpectedOrdererIp).
add_string(   gcOrderStruct,"payment_method"      ,gcExpectedPaymentMethod).
add_string(   gcOrderStruct,"payment_reference"   ,gcExpectedCCReference).
add_string(   gcOrderStruct,"person_id"           ,gcExpectedPersonId).
add_string(   gcOrderStruct,"salesman"            ,gcExpectedSalesman).
add_string(   gcOrderStruct,"services"            ,gcExpectedServices).
add_string(   gcOrderStruct,"subscription_type"   ,gcExpectedCLIType).
add_string(   gcOrderStruct,"subscription_type"   ,gcExpectedSubscriptionType).
add_double(   gcOrderStruct,"topup"               ,gdeExpectedTopup).
add_string(   gcOrderStruct,"user_fname"          ,gcExpectedUserFName).
add_string(   gcOrderStruct,"user_lname"          ,gcExpectedUserLName).
add_string(   gcOrderStruct,"user_lname2"         ,gcExpectedUserLName2).

