DEF VAR gcExpectedAccount             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddress             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressCity         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressCodC         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressCodP         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressConame       AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressContactName  AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressCountry      AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressCustomerName AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressEmail        AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressFName        AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressLName        AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressLName2       AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressNationality  AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressPhoneNumber  AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressRegion       AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressSiteName     AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressSmsNumber    AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressStreet       AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressTitle        AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedAddressZip          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedBrand               AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCampaign            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCCReference         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedChannel             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCLI                 AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCLIType             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCodC                AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCodP                AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCompany             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCompanyId           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCoName              AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedContractID          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCountry             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCreUser             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCreUser2            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCurrOper            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCustID              AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedCustIDType          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedDeviceId            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedDeviceModel         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedEmail               AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedFeeModel            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedFixedNumber         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedFName               AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedHostTable           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedICC                 AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedIdType              AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedIMEI                AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedKeyValue            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedLanguage            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedLName               AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedLName2              AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMemoSeq             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMemoText            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMemoText2           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMemoText3           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMemoTitle           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMemoTitle2          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMemoTitle3          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedMsisdnStatusCode    AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedNationality         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedNumberType          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedOldBillCategory     AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedOldICC              AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedOrderer             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedOrdererID           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedOrdererIdType       AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedOrdererIp           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedOrderID             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedParamChannel        AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedParamDeviceModel    AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedParamIdType         AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedParamIMEI           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedParamLanguage       AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedPaymentMethod       AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedPaymentReference    AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedPersonId            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedPostOffice          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedRegion              AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSalesman            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSecOrdCustLanguage  AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSecOrdCustNational  AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSecOrdCustrCountry  AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedServices            AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSMSNumber           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSource              AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedStatusCode          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSubscriptionType    AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedSurName             AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedTestDescription     AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedTitle               AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedUserFName           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedUserLName           AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedUserLName2          AS CHARACTER             NO-UNDO.
DEF VAR gcExpectedZipCode             AS CHARACTER             NO-UNDO.
DEF VAR gdaExpectedAddressBirthDay    AS DATE             NO-UNDO.
DEF VAR gdaExpectedBirthDay           AS DATE             NO-UNDO.
DEF VAR gdeExpectedCreStamp           AS DECIMAL             NO-UNDO.
DEF VAR gdeExpectedDevicePrice        AS DECIMAL             NO-UNDO.
DEF VAR gdeExpectedDiscount           AS DECIMAL             NO-UNDO.
DEF VAR gdeExpectedFAT                AS DECIMAL             NO-UNDO.
DEF VAR gdeExpectedParamDevicePrice   AS DECIMAL             NO-UNDO.
DEF VAR gdeExpectedTopup              AS DECIMAL             NO-UNDO.
DEF VAR giExpectedAddressLanguage     AS INTEGER             NO-UNDO.
DEF VAR giExpectedInvCustrole         AS INTEGER             NO-UNDO.
DEF VAR giExpectedMemoSeq             AS INTEGER             NO-UNDO.
DEF VAR giExpectedMethod              AS INTEGER             NO-UNDO.
DEF VAR giExpectedMnpStatus           AS INTEGER             NO-UNDO.
DEF VAR giExpectedMsSeq               AS INTEGER             NO-UNDO.
DEF VAR giExpectedOrderId             AS INTEGER             NO-UNDO.
DEF VAR giExpectedRowType             AS INTEGER             NO-UNDO.
DEF VAR giExpectedSIMStatus           AS INTEGER             NO-UNDO.
DEF VAR giExpectedStatusCode          AS INTEGER             NO-UNDO.
DEF VAR giExpectedUserRole            AS INTEGER             NO-UNDO.
DEF VAR glExpectedAddressMarkEmail    AS LOGICAL             NO-UNDO.
DEF VAR glExpectedAddressMarkEmail3rd AS LOGICAL             NO-UNDO.
DEF VAR glExpectedAddressMarkPost     AS LOGICAL             NO-UNDO.
DEF VAR glExpectedAddressMarkPost3rd  AS LOGICAL             NO-UNDO.
DEF VAR glExpectedAddressMarkSMS      AS LOGICAL             NO-UNDO.
DEF VAR glExpectedAddressMarkSMS3rd   AS LOGICAL             NO-UNDO.
DEF VAR glExpectedCheck               AS LOGICAL             NO-UNDO.
DEF VAR glExpectedMarkEmail           AS LOGICAL             NO-UNDO.
DEF VAR glExpectedMarkEmail3rd        AS LOGICAL             NO-UNDO.
DEF VAR glExpectedMarkPost            AS LOGICAL             NO-UNDO.
DEF VAR glExpectedMarkPost3rd         AS LOGICAL             NO-UNDO.
DEF VAR glExpectedMarkSMS             AS LOGICAL             NO-UNDO.
DEF VAR glExpectedMarkSMS3rd          AS LOGICAL             NO-UNDO.
DEF VAR glExpectedMnpProcessBypass    AS LOGICAL             NO-UNDO.
DEF VAR glExpectedNetworkBypass       AS LOGICAL             NO-UNDO.
DEF VAR glExpectedNoCharge            AS LOGICAL             NO-UNDO.
DEF VAR glExpectedOldPayType          AS LOGICAL             NO-UNDO.
DEF VAR glExpectedOperAllMarketing    AS LOGICAL             NO-UNDO.
DEF VAR glExpectedPayType             AS LOGICAL             NO-UNDO.
DEF VAR gcExpectedAddressParamLanguage AS CHARACTER          NO-UNDO.
DEF VAR gdaExpectedContactBirthDay    AS DATE                NO-UNDO.
DEF VAR gcExpectedContactCity         AS CHARACTER           NO-UNDO.
DEF VAR gcExpectedContactCodC         AS CHARACTER           NO-UNDO.

