from gearbox.migrations import Migration

class AddTableFixedFee(Migration):

    database = "common"

    def up(self):
        t = self.table('FixedFee', area="Sta_Data_32", label="Constant / Contract Fees", table_trigger=[{'crc': '?', 'procedure': 'triggers/rd-fixedfee.p', 'override_proc': True, 'event': 'REPLICATION-DELETE'}, {'crc': '?', 'procedure': 'triggers/rw-fixedfee.p', 'override_proc': True, 'event': 'REPLICATION-WRITE'}], dump_name="fixedfee", desc="Constant / contract fees")
        t.column('CustNum', 'integer', mandatory=True, format=">>>>>>>>9", initial="0", max_width=4, label="Customer", column_label="Customer", position=2, order=20, help="Customer number")
        t.column('BillCode', 'character', format="x(6)", initial="", max_width=12, label="Product", column_label="Product", position=3, order=30, help="Product code")
        t.column('Memo', 'character', format="x(60)", initial="", max_width=610, label="MemoExp", column_label="MemoExp", extent=5, position=4, order=40, help="Explanation text for the invoice")
        t.column('Amt', 'decimal', format="->>>,>>9.99", decimals=2, initial="0", max_width=17, label="To Pay", column_label="To Pay", position=5, order=50, help="Contract payment per bill")
        t.column('Interval', 'integer', valexp="Interval > 0 and Interval < 13", format="z9", initial="0", max_width=4, label="Interval", column_label="Interval", position=6, order=60, valmsg="Invoicing interval must be between 1 and 12 !", help="\"Invoicing interval; number of months betw. 2 consecutive bills\"")
        t.column('OwnCost', 'decimal', format="->>>,>>9.99", decimals=2, initial="0", help="Our own costs per bill", max_width=17, label="Our costs", column_label="Our costs", position=7, order=70, description="Our own costs per bill")
        t.column('FFNum', 'integer', format="zzzzzzz9", initial="0", max_width=4, label="Contract", column_label="Contract", position=8, order=10, help="Consecutive number (sequence) of contract")
        t.column('BegPeriod', 'integer', format="999999", initial="0", max_width=4, label="FromPer", column_label="FromPer", position=9, order=80, help="1. Period YYYYMM (month when a service was DELIVERED)")
        t.column('EndPeriod', 'integer', format="999999", initial="999999", max_width=4, label="ExpPer", column_label="ExpPer", position=10, order=90, help="Last Period YYYYMM (month when a service was DELIVERED)")
        t.column('BillMethod', 'integer', valexp="BillMethod > 0 and BillMethod < 4", format="9", initial="3", max_width=4, label="Type", column_label="Type", position=11, order=100, valmsg="Type code MUST be 1, 2 or 3 !", help="When this fee is to be billed: 1:before 2:during 3:after MONTH")
        t.column('Active', 'logical', format="Yes/No", initial="no", max_width=1, label="Active", column_label="Active", position=12, order=110, help="Is this contract active ?")
        t.column('InUse', 'logical', format="Yes/No", initial="Yes", max_width=1, label="Used", column_label="Used", position=13, order=120, help="Is this payment in use ?")
        t.column('xxInclVat', 'logical', format="Yes/No", initial="y", max_width=1, label="VAT", column_label="VAT", position=14, order=130, help="Shall VAT be added when billed (Y/N) ?")
        t.column('CalcObj', 'character', format="x(16)", initial="", max_width=32, label="CalcObject", column_label="CalcObject", position=15, order=140, help="Calculation Object Within Customer/InvTarg/Billing Level")
        t.column('CLI', 'character', format="x(12)", initial="", max_width=24, label="A-Subscriber", column_label="A-Sub", position=16, order=151, help="A-Subscriber number")
        t.column('BegDate', 'date', format="99-99-9999", initial=self.unknown, max_width=4, label="ContDate", column_label="ContDate", position=17, order=161, help="Date of Contract")
        t.column('HostTable', 'character', format="x(16)", initial="", max_width=32, label="HostTable", column_label="HostTable", position=18, order=150, help="HostTable")
        t.column('KeyValue', 'character', format="x(20)", initial="", max_width=40, label="KeyValue", column_label="KeyValue", position=19, order=160, help="KeyValue")
        t.column('CustPP', 'integer', format="->>>>>>9", initial="0", max_width=4, label="Seq", column_label="Seq", position=20, order=170, help="Internal sequence no of Contract/Product Pack")
        t.column('FeeModel', 'character', format="x(8)", initial="", max_width=16, label="BEvent", column_label="BEvent", position=21, order=180, help="Code of Billing Event")
        t.column('InclAmt', 'decimal', format="->>>>>9.99", decimals=2, initial="0", max_width=17, label="Included Amount", column_label="Incl.Amt", position=22, order=190, help="Amount of billable material that is included in this fee")
        t.column('InclBillCode', 'character', format="x(16)", initial="", max_width=32, label="Incl.Billing Item", column_label="Incl.BItem", position=23, order=201, help="Billing item that included amount concerns")
        t.column('InclUnit', 'integer', format=">9", initial="0", max_width=4, label="Included Unit", column_label="Incl.Unit", position=24, order=210, help="Unit of included material")
        t.column('Brand', 'character', format="x(8)", initial="", max_width=16, label="Brand", column_label="Brand", position=25, order=220, help="Code Of Brand")
        t.column('Contract', 'character', format="x(8)", initial="", max_width=16, label="Contract ID", column_label="ContrID", position=26, order=230, help="Contract ID")
        t.column('VatIncl', 'logical', format="Included/Excluded", initial="Yes", max_width=1, label="VAT Included", column_label="VAT", position=27, order=200, help="Is VAT included or excluded in prices")
        t.column('ServiceLimitGroup', 'character', format="x(16)", initial="", max_width=32, label="ServiceLimitGroup", column_label="ServiceLimitGroup", position=28, order=240, help="Group Code of Service Limit")
        t.column('FinancedResult', 'character', format="x(8)", initial="", max_width=16, label="FinancedResult", column_label="FinancedResult", position=29, order=250, help="Financed result code")
        t.column('OrderId', 'integer', format=">>>>>>>>9", initial="0", max_width=4, label="OrderId", column_label="OrderId", position=30, order=260)
        t.column('SourceTable', 'character', format="x(12)", initial="", max_width=24, label="SourceTable", column_label="SourceTable", position=31, order=270)
        t.column('SourceKey', 'character', format="x(12)", initial="", max_width=24, label="SourceKey", column_label="SourceKey", position=32, order=280)
        t.column('CalcAmt', 'decimal', format="->>>,>>9.99", decimals=2, initial=self.unknown, max_width=17, label="Calculated Amount", column_label="CalcAmt", position=33, order=290)
        t.column('TFBank', 'character', format="X(8)", initial="", max_width=16, label="TFBank", column_label="TFBank", position=34, order=300, help="Terminal Financing Bank Code")
        t.column('IFSStatus', 'integer', format=">>9", initial="0", max_width=4, label="IFS Status", column_label="IFSStatus", position=35, order=310)
        t.index('CustNum', [['Brand'], ['CustNum'], ['HostTable'], ['KeyValue'], ['EndPeriod', 'DESC']], area="Sta_Index_1", primary=True)
        t.index('BillCode', [['Brand'], ['BillCode'], ['CustNum']], area="Sta_Index_1")
        t.index('Contract', [['Brand'], ['Contract'], ['BillCode']], area="Sta_Index_1")
        t.index('CustNum_s', [['CustNum'], ['BillCode']], area="Sta_Index_1")
        t.index('CustPP', [['Brand'], ['CustPP']], area="Sta_Index_1")
        t.index('FeeModel', [['Brand'], ['FeeModel']], area="Sta_Index_1")
        t.index('FFNum', [['FFNum']], area="Sta_Index_1", unique=True)
        t.index('FinancedResult', [['FinancedResult']], area="Sta_Index_3")
        t.index('HostTable', [['Brand'], ['HostTable'], ['KeyValue', 'ABBREVIATED']], area="Sta_Index_1")
        t.index('IFSstatus', [['IFSStatus']], area="Sta_Index_4")
        t.index('used', [['Brand'], ['CustNum'], ['InUse']], area="Sta_Index_1")

    def down(self):
        self.drop_table('FixedFee')
