from gearbox.migrations import Migration

class AddTableSingleFee(Migration):

    database = "common"

    def up(self):
        t = self.table('SingleFee', area="Sta_Data_32", label="Single Fee", table_trigger=[{'crc': '?', 'procedure': 'triggers/rd-singlefee.p', 'override_proc': True, 'event': 'REPLICATION-DELETE'}, {'crc': '?', 'procedure': 'triggers/rw-singlefee.p', 'override_proc': True, 'event': 'REPLICATION-WRITE'}], dump_name="singlefe", desc="Single billable fee")
        t.column('FMItemId', 'integer', format="zzzzzzzz9", initial="0", max_width=4, label="ItemNo", column_label="ItemNo", position=2, order=10, help="\"Individual \"\"invisible\"\" sequence for this item\"")
        t.column('BillPeriod', 'integer', format="999999", initial="0", max_width=4, label="Period", column_label="Period", position=3, order=20, help="Period YYYYMM (month when this item shall be BILLED)")
        t.column('Amt', 'decimal', format="->,>>>,>>9.99", decimals=2, initial="0", max_width=17, label="Amount", column_label="Amount", position=4, order=30, help="Payable Amount ex VAT")
        t.column('OwnCost', 'decimal', format="->,>>>,>>9.99", decimals=2, initial="0", max_width=17, label="Our costs", column_label="Our costs", position=5, order=40, help="Our own costs per bill")
        t.column('Billed', 'logical', format="yes/no", initial="no", max_width=1, label="Billed", column_label="Billed", position=6, order=50, help="Is this item billed (y/n)")
        t.column('InvNum', 'integer', format="zzzzzzzzz", initial="0", max_width=4, label="InvNo", column_label="InvNo", position=7, order=60, help="Number of an invoice where this item was billed")
        t.column('BillCode', 'character', format="x(16)", initial="", max_width=32, label="Product", column_label="Product", position=8, order=70, help="Product code")
        t.column('Memo', 'character', format="x(60)", initial="", max_width=610, label="Explanation", column_label="Explanation", extent=5, position=9, order=80, help="Individual Explanation Text for the invoice")
        t.column('CustNum', 'integer', mandatory=True, format=">>>>>>>>9", initial="0", max_width=4, label="Customer", column_label="Customer", position=10, order=90, help="Customer number")
        t.column('Concerns', 'integer', format="999999", initial="0", max_width=28, label="Concerns", column_label="Concerns", extent=2, position=11, order=120, help="Period that this fee concerns")
        t.column('BillLevel', 'character', format="x(10)", initial="", max_width=20, label="Level", column_label="Level", position=12, order=110, help="Hierarchical Billing Level code")
        t.column('InvRowId', 'integer', format=">>>>>>>9", initial="0", max_width=4, label="InvRowId", column_label="InvRowId", position=13, order=130, help="Invoice row identification number")
        t.column('BillTarget', 'integer', format="z9", initial="0", max_width=4, label="No", column_label="No", position=14, order=100, help="Consecutive No. for Customer's Invoicing Target")
        t.column('CalcObj', 'character', format="x(16)", initial="", max_width=32, label="CalcObject", column_label="CalcObject", position=15, order=140, help="Calculation Object Within Customer/InvTarg/Billing Level")
        t.column('MiscInt', 'integer', format="zzzzzzzz9", initial="0", max_width=200, label="Integer", column_label="Integer", extent=10, position=16, order=150, help="Miscellaneous integer data")
        t.column('MiscDec', 'decimal', format="zzzzz9.99999", decimals=2, initial="0", max_width=260, label="Decimal", column_label="Decimal", extent=10, position=17, order=160, help="Miscellaneous decimal data")
        t.column('BillType', 'character', format="x(8)", initial="", max_width=16, label="Billing Type", column_label="Billing Type", position=18, order=170, help="Billing type")
        t.column('VATCode', 'integer', format="z9", initial="1", max_width=4, label="VAT code", column_label="VAT code", position=19, order=181, help="VAT code 1 ... 10")
        t.column('CLI', 'character', format="x(12)", initial="", max_width=24, label="A-Subscriber", column_label="A-Sub", position=20, order=191, help="A-Subscriber number")
        t.column('HostTable', 'character', format="x(16)", initial="", max_width=32, label="HostTable", column_label="HostTable", position=21, order=180, help="HostTable")
        t.column('KeyValue', 'character', format="x(20)", initial="", max_width=40, label="KeyValue", column_label="KeyValue", position=22, order=190, help="KeyValue")
        t.column('FeeModel', 'character', format="x(8)", initial="", max_width=16, label="BEvent", column_label="BEvent", position=23, order=200, help="Code of Billing Event")
        t.column('CustPP', 'integer', format="->>>>>>9", initial="0", max_width=4, label="Seq", column_label="Seq", position=24, order=210, help="Internal sequence no of Contract/Product Pack")
        t.column('Brand', 'character', format="x(8)", initial="", max_width=16, label="Brand", column_label="Brand", position=25, order=220, help="Code Of Brand")
        t.column('Contract', 'character', format="x(8)", initial="", max_width=16, label="Contract ID", column_label="ContrID", position=26, order=230, help="Contract ID")
        t.column('VatIncl', 'logical', format="Included/Excluded", initial="Yes", max_width=1, label="VAT Included", column_label="VAT", position=27, order=241, help="Is VAT included or excluded in prices")
        t.column('Active', 'logical', format="Yes/No", initial="Yes", max_width=1, label="Active", position=28, order=250, help="Is fee active (i.e. billable)")
        t.column('ServiceLimitGroup', 'character', format="x(16)", initial="", max_width=32, label="ServiceLimitGroup", column_label="ServiceLimitGroup", position=29, order=240, help="Group Code of Service Limit")
        t.column('SubInvNum', 'integer', format=">>9", initial="0", max_width=4, label="SubInvoice Number", column_label="SubInv", position=30, order=260, help="Sequential nbr of the subinvoice within the combined invoice")
        t.column('SourceTable', 'character', format="x(12)", initial="", max_width=24, label="SourceTable", column_label="SourceTable", position=31, order=270)
        t.column('SourceKey', 'character', format="x(12)", initial="", max_width=24, label="SourceKey", column_label="SourceKey", position=32, order=280)
        t.column('OrderId', 'integer', format="->>>>>>>>9", initial="0", max_width=4, label="OrderId", column_label="OrderId", position=33, order=290)
        t.index('CustNum_s', [['CustNum'], ['BillPeriod'], ['Billed']], area="Sta_Index_2", primary=True)
        t.index('BillCode', [['Brand'], ['BillCode'], ['CustNum']], area="Sta_Index_2")
        t.index('CalcObj', [['Brand'], ['CalcObj']], area="Sta_Index_2")
        t.index('Contract', [['Brand'], ['Contract'], ['BillCode']], area="Sta_Index_2")
        t.index('CustNum', [['Brand'], ['CustNum'], ['HostTable'], ['KeyValue'], ['BillPeriod', 'DESC']], area="Sta_Index_2")
        t.index('FMItemId', [['Brand'], ['FMItemId']], area="Sta_Index_2", unique=True)
        t.index('HostTable', [['Brand'], ['HostTable'], ['KeyValue', 'ABBREVIATED']], area="Sta_Index_2")
        t.index('InvNum', [['Brand'], ['CustNum'], ['InvNum']], area="Sta_Index_2")
        t.index('InvNum_s', [['InvNum']], area="Sta_Index_2")

    def down(self):
        self.drop_table('SingleFee')
