from gearbox.migrations import Migration

class AddTableCustomer(Migration):

    database = "common"

    def up(self):
        t = self.table('Customer', area="Sta_Data_32_2", label="Customer", table_trigger=[{'crc': '?', 'procedure': 'rd-customer.p', 'override_proc': True, 'event': 'REPLICATION-DELETE'}, {'crc': '?', 'procedure': 'rw-customer.p', 'override_proc': True, 'event': 'REPLICATION-WRITE'}], dump_name="custome1", desc="Customer")
        t.column('CustNum', 'integer', mandatory=True, format=">>>>>>>>9", initial="0", max_width=4, label="Customer", column_label="Customer", position=2, order=10, help="Customer's number")
        t.column('CustName', 'character', format="x(30)", initial="", max_width=60, label="Customer's name", column_label="Customer's name", position=3, order=70, help="Customer's name")
        t.column('COName', 'character', format="x(30)", initial="", max_width=60, label="Addt'l name", column_label="Addt'l name", position=4, order=120, help="Additional name of a customer")
        t.column('Address', 'character', format="x(30)", initial="", max_width=60, label="Address", column_label="Address", position=5, order=130, help="Customer's mailing address (street, p.o. box)")
        t.column('ZipCode', 'character', format="x(8)", initial="", max_width=16, label="Postal code", column_label="Postcd", position=6, order=140, help="Customer's postal code")
        t.column('PostOffice', 'character', format="x(24)", initial="", max_width=48, label="Postal Addr.", column_label="Postaddr", position=7, order=150, help="Customer's postal address")
        t.column('Country', 'character', format="x(3)", initial="", max_width=6, label="Country", column_label="Country", position=8, order=160, help="Customer's country code")
        t.column('SearchName', 'character', format="x(8)", initial="", max_width=16, label="Abbrev", column_label="Abbrev", position=9, order=20, help="Alphanumeric key for browsing")
        t.column('InvCust', 'integer', format="ZZZZZZZZ9", initial="0", max_width=4, label="Invoice Cust.", column_label="Inv.Cust", position=10, order=30, help="Customer being billed")
        t.column('PaymCust', 'integer', format="ZZZZZZZZ9", initial="0", max_width=4, label="Paym.resp.", column_label="Paymresp", position=11, order=50, help="Number of customer who is responsible for payment")
        t.column('RateCust', 'integer', format="ZZZZZZZZ9", initial="0", max_width=4, label="DiscCust", column_label="DiscCust", position=12, order=40, help="Customer whose rates and discounts shall be used")
        t.column('Salesman', 'character', format="x(8)", initial="", max_width=16, label="Salesman", column_label="Salesman", position=13, order=170, help="Salesman who is responsible for customer")
        t.column('RepCodes', 'character', format="x(30)", initial="", max_width=60, label="Report Codes", column_label="Reports", position=15, order=180, help="Report definition")
        t.column('RepCust', 'integer', format="ZZZZZZZZ9", initial="0", max_width=4, label="RapCust", column_label="RapCust", position=16, order=60, help="Customer who receives call report(s)")
        t.column('Contact', 'character', format="x(30)", initial="", max_width=60, label="Contact", column_label="Contact", position=17, order=80, help="Contact name")
        t.column('Phone', 'character', format="x(16)", initial="", max_width=32, label="PhoneNo", column_label="PhoneNo", position=18, order=90, help="Customer's phone number")
        t.column('Fax', 'character', format="x(16)", initial="", max_width=32, label="Fax", column_label="Fax", position=19, order=100, help="Customer's fax no.")
        t.column('Language', 'integer', valexp="Language > 0", format=">>9", initial="0", max_width=4, label="Language", column_label="Language", position=20, order=200, valmsg="Must be 1 ... 9 !", help="Customer's language code (1 ...999)")
        t.column('PaymTerm', 'integer', format=">9", initial="0", max_width=4, label="Payment Terms", column_label="Payment Terms", position=21, order=210, help="Terms of payment (days)")
        t.column('OrgId', 'character', format="x(11)", initial="", max_width=22, label="Pers/Comp.ID", position=22, order=220, help="Customer's organisation ID or personal ID")
        t.column('Email', 'character', format="x(60)", initial="", max_width=120, label="Email", column_label="Email", position=23, order=110, help="Customer's Email ID")
        t.column('Category', 'character', format="x(4)", initial="", max_width=8, label="Cat", column_label="Cat", position=24, order=230, help="Category code, max 4 characters")
        t.column('ContrBeg', 'date', format="99-99-9999", max_width=4, label="Cstart", column_label="Cstart", position=25, order=240, help="Day when contract was begun")
        t.column('ContrEnd', 'date', format="99-99-9999", max_width=4, label="End Date", column_label="End Date", position=26, order=250, help="Day when contract was ended")
        t.column('xxMemo', 'character', format="x(60)", initial="", max_width=1830, label="Memo", column_label="Memo", extent=15, position=27, order=260, help="Memo (text)")
        t.column('ClaimPerm', 'logical', format="Yes/No", initial="yes", max_width=1, label="DueCond", column_label="DueCond", position=28, order=270, help="Send a payment reminder of the invoice (Y/N)")
        t.column('InterestPerm', 'logical', format="Yes/No", initial="yes", max_width=1, label="IntCond", column_label="IntCond", position=29, order=280, help="Charge a overtime interest to customer (Y/N)")
        t.column('CashDiscDate', 'integer', format="z9", initial="0", max_width=4, label="CashDisc", column_label="CashDisc", position=30, order=290, help="Cash discount")
        t.column('CashDiscPerc', 'decimal', format="z9.9", decimals=2, initial="0", max_width=17, label="CashDisc-%", column_label="CashDisc-%", position=31, order=300, help="Cash discount percent")
        t.column('PaymMethod', 'integer', format="zzz9-", initial="0", max_width=4, label="MethOfPaym", column_label="MethOfPaym", position=32, order=310, help="Customer's payment behavior (days +/- dueday)")
        t.column('InvoiceTargetRule', 'integer', format="9", initial="0", max_width=4, label="Invoice Target Rule", column_label="IT Rule", position=33, order=320, help="Rule for adding new invoice targets")
        t.column('LatestPaym', 'date', format="99-99-99", max_width=4, label="LastPaymDay", column_label="LastPaymDay", position=34, order=330, help="Previous day when customer has paid ")
        t.column('PriceList', 'character', format="x(8)", initial="", max_width=16, label="Price List", column_label="Price List", position=36, order=350, help="Code (identifier) for a Price List")
        t.column('InvGroup', 'character', format="x(8)", initial="", max_width=16, label="InvGroup", column_label="InvGroup", position=37, order=360, help="Alphanumeric code for Invoicing Group")
        t.column('CreUser', 'character', format="x(8)", initial="", max_width=16, label="Created by", column_label="Created by", position=38, order=370, help="User who created this customer")
        t.column('CreDate', 'date', format="99-99-99", max_width=4, label="Created", column_label="Created", position=39, order=381, help="Date of creation")
        t.column('UpdDate', 'date', format="99-99-99", max_width=4, label="Updated", column_label="Updated", position=40, order=390, help="Date of latest updation")
        t.column('UpdUser', 'character', format="x(8)", initial="", max_width=16, label="Updated by", column_label="Updated by", position=41, order=400, help="User who updated this customer latest")
        t.column('Size', 'character', mandatory=True, valexp="lookup(size,""XL,L,M,S,"") > 0", format="x(2)", initial="M", max_width=4, label="Size", column_label="Size", position=42, order=410, valmsg="Answer XL/L/M/S !", help="Size of customer: (XL)arge, (L)arge, (M)edium, (S)mall")
        t.column('ConnType', 'logical', format="Direct/Indirect", initial="no", max_width=1, label="Connection", column_label="Connection", position=43, order=420, help="Type of subscriber: (D)irect, (I)ndirect")
        t.column('Reseller', 'character', format="x(8)", initial="", max_width=16, label="Reseller", column_label="Reseller", position=44, order=380, help="An unique code for a reseller; maximum 8 characters")
        t.column('StartCharge', 'logical', format="A/P", initial="Yes", max_width=1, label="Start charge", column_label="Start charge", position=45, order=430, help="Allow / Prohibit starting charges for this customer (A/P)")
        t.column('VolDisc', 'logical', format="Allow/Prohibit", initial="no", max_width=1, label="VolDisc", column_label="VolDisc", position=47, order=450, help="Is volume discount allowed after net rates (A/P) ?")
        t.column('VATUsage', 'integer', format="9", initial="1", max_width=4, label="VAT Usage", column_label="VAT", position=49, order=480, help="How VAT is calculated for this customer")
        t.column('Currency', 'character', format="x(5)", initial="", max_width=10, label="Currency", column_label="Currency", position=50, order=490, help="Currency code")
        t.column('VATId', 'character', format="x(16)", initial="", max_width=32, label="VAT Id", column_label="VAT Id", position=51, order=500, help="VAT Id")
        t.column('ChgStamp', 'decimal', format="99999999.99999", decimals=5, initial="0", help="Date and Time When Customer Record was last changed", max_width=20, label="Created", column_label="Created", position=54, order=900, description="Time Stamp yyyymmdd.time (sec)")
        t.column('ExpStamp', 'decimal', format="99999999.99999", decimals=5, initial="0", help="Date and Time when this record was last exported to", max_width=20, label="Xferred", column_label="Xferred", position=55, order=910, description="Time Stamp yyyymmdd.time (sec)")
        t.column('LatestInv', 'integer', format="999999", initial="0", max_width=4, label="InvPeriod", column_label="InvPeriod", position=56, order=920, help="Period of latest invoice")
        t.column('InvInterval', 'integer', format=">9", initial="0", max_width=4, label="InvInterval", column_label="InvInterval", position=57, order=930, help="Interval for invoicing (months)")
        t.column('BankAcct', 'character', format="x(16)", initial="", max_width=32, label="BankAccount", column_label="BankAccount", position=59, order=1000, help="Customer's Bank  Account No  (for DirectDebit purposes)")
        t.column('DDStatus', 'integer', format="9", initial="0", max_width=4, label="Debit status", column_label="Debit status", position=60, order=1100, help="DirDebitStatus: 0:No DD  1:New  2:Sent to bank  3:Confirmed")
        t.column('WInvDisp', 'logical', format="Yes/No", initial="no", max_width=1, label="Web", column_label="Web", position=61, order=970, help="Allow displaying in WEB Phone Book")
        t.column('Pocket', 'integer', format="999999", max_width=4, label="Pocket", column_label="Pocket", position=63, order=960, help="Pocket")
        t.column('ChargeType', 'integer', format="9", initial="1", help="Customers default charging type", max_width=4, label="Charge Type", column_label="Charge", position=67, order=1120, description="3=netgiro")
        t.column('DelType', 'integer', format="9", initial="0", max_width=4, label="Delivery Type", column_label="Del.Type", position=68, order=1130, help="Customers invoice delivery type")
        t.column('BankId', 'character', format="X(10)", initial="", max_width=20, label="BankId", column_label="BankId", position=69, order=1110, help="Identification code for bank")
        t.column('HonTitle', 'character', format="x(16)", initial="", max_width=32, label="Title", column_label="Title", position=70, order=1121, help="Customer honorary title (printed f.ex. into invoice)")
        t.column('AccGrp', 'integer', format=">>9", initial="1", max_width=4, label="Account Group", column_label="AccGrp", position=74, order=1040, help="Sales: 1:inside own country, 2:inside EU, 3:outside EU")
        t.column('InvCode', 'integer', format="99", initial="0", max_width=4, label="Invoice Code", column_label="Invoice Code", position=75, order=1160, help="Code for week / day of a month for used invoice run (99)")
        t.column('OutMarkEmail', 'logical', format="yes/no", initial="no", help="3rd party marketing using eMail", max_width=1, label="Out. Marketing Via Email", column_label="Out.Mark.Email", position=76, order=1360, description='''

''')
        t.column('NeteMail', 'character', format="x(40)", initial="", max_width=80, label="eMail (Internet)", column_label="Net eMail", position=77, order=1090, help="eMail for the person in charge of internet related things")
        t.column('Brand', 'character', format="x(8)", initial="", max_width=16, label="Brand", column_label="Brand", position=78, order=1180, help="Code Of Brand")
        t.column('CustClass', 'integer', format="9", initial="0", max_width=4, label="Class", column_label="Class", position=79, order=1190, help="Customer Class (depend on avg. amount of invoices)")
        t.column('VATIncl', 'logical', format="Included/Excluded", initial="yes", max_width=1, label="VAT Included", column_label="VATIncl", position=80, order=1200, help="Format for invoices; is VAT included or excluded in amounts")
        t.column('DirMark', 'character', format="x(12)", initial="", max_width=24, label="DirectMarketing", column_label="DirectMarketing", position=82, order=1050, help="Direct marketing codes")
        t.column('NewCust', 'logical', format="Yes/No", initial="no", max_width=1, label="NewCustomer", column_label="NewCustomer", position=83, order=1060, help="New customer")
        t.column('CcLang', 'character', format="x(8)", initial="", max_width=16, label="Conv. language", column_label="Lang.", position=84, order=1070, help="Conversation language")
        t.column('MobeMail', 'character', format="x(40)", initial="", max_width=80, label="eMail (Mobile)", column_label="Mob eMail", position=85, order=1080, help="eMail for person in charge of mobile related things")
        t.column('CreditLimit', 'decimal', format="->>>>>>>9.99", decimals=2, initial="0", max_width=17, label="Credit Limit", column_label="CredLimit", position=86, order=1221, help="Credit limit")
        t.column('SpecDel', 'integer', format="9", initial="0", max_width=4, label="Specification Delivery", column_label="Spec Del.", position=87, order=1231, help="Specification report delivery type")
        t.column('AgrCust', 'integer', format=">>>>>>>9", initial="0", max_width=4, label="Agreement Customer", column_label="Agr.Cust", position=88, order=1210, help="Agreement customer")
        t.column('IDelName', 'character', format="x(30)", initial="", max_width=60, label="Delivery Name", column_label="Del.Name", position=89, order=1220, help="Invoice delivery name")
        t.column('IDelAddr', 'character', format="x(30)", initial="", max_width=60, label="Delivery Address", column_label="Del.Address", position=90, order=1230, help="Invoice delivery address")
        t.column('IDelZipCode', 'character', format="x(8)", initial="", max_width=16, label="Delivery Zip Code", column_label="Del.ZipCode", position=91, order=1240, help="Invoice delivery zip code")
        t.column('IDelPost', 'character', format="x(30)", initial="", max_width=60, label="Delivery Post Office", column_label="Del.Post", position=92, order=1250, help="Invoice delivery post office")
        t.column('IDelCountry', 'character', format="x(30)", initial="", max_width=60, label="Delivery Country", column_label="Del.Country", position=93, order=1260, help="Invoice delivery country")
        t.column('IDelCOName', 'character', format="x(30)", initial="", max_width=60, label="Delivery Add.Name", column_label="Del.AName", position=94, order=1270, help="Additional invoice delivery name")
        t.column('SMSNumber', 'character', format="x(15)", initial="", max_width=30, label="SMS Number", column_label="SMS", position=95, order=1280, help="Mobile number for SMS messages")
        t.column('Roles', 'character', format="x(3)", initial="", max_width=6, label="Roles", column_label="Role", position=96, order=1290, help="Customer's roles (agreement, invoicing, user)")
        t.column('FirstName', 'character', format="x(20)", initial="", max_width=40, label="Forename", column_label="Forename", position=97, order=1300, help="Customer's forename")
        t.column('DirMarkSMS', 'logical', format="yes/no", initial="no", max_width=1, label="Direct Marketing Via SMS", column_label="Dir.Mark.SMS", position=98, order=1310, help="Direct marketing using SMS")
        t.column('DirMarkEmail', 'logical', format="yes/no", initial="no", max_width=1, label="Direct Marketing Via Email", column_label="Dir.Mark.Email", position=99, order=1320, help="Direct marketing using Email")
        t.column('DirMarkPost', 'logical', format="yes/no", initial="no", max_width=1, label="Direct Marketing Via Post", column_label="Dir.Mark.Post", position=100, order=1330, help="Direct marketing using post")
        t.column('OutMarkPost', 'logical', format="yes/no", initial="no", max_width=1, label="Out. Marketing Via Post", column_label="Out.Mark.Post", position=101, order=1340, help="3rd part marketing using post")
        t.column('OutMarkSMS', 'logical', format="yes/no", initial="no", help="3rd party marketing using SMS", max_width=1, label="Out. Marketing Via SMS", column_label="Out.Mark.SMS", position=102, order=1350, description='''


''')
        t.column('PContractPIN', 'character', format="x(8)", initial="", max_width=16, label="Periodical Contract PIN", column_label="PC PIN", position=103, order=1370, help="PIN for periodical contract")
        t.column('EndInvType', 'integer', format="9", initial="0", max_width=4, label="End Invoice Type", column_label="EndInv.Type", position=105, order=1390, help="End invoice type")
        t.column('EndInvDate', 'date', format="99-99-99", max_width=4, label="End Invoice Date", column_label="EndInvRun", position=106, order=1400, help="Date when end invoice run was performed")
        t.column('CustIdType', 'character', format="x(8)", initial="", help="Customer ID type", max_width=16, label="Customer ID Type", column_label="ID Type", position=107, order=1410, description='''

''')
        t.column('Nationality', 'character', format="x(8)", initial="", help="Nationality", max_width=16, label="Nationality", column_label="Nation.", position=108, order=1420, description='''

''')
        t.column('SurName2', 'character', format="x(30)", initial="", help="Second surname", max_width=60, label="Second Surname", column_label="2.Surname", position=109, order=1430, description='''
''')
        t.column('Sex', 'character', format="x(8)", initial="", max_width=16, label="Sex", position=110, order=1440, help="Sex")
        t.column('Region', 'character', format="x(8)", initial="", help="Region code", max_width=16, label="Region", position=111, order=1450, description='''

''')
        t.column('RobinsonsLimit', 'character', format="x(8)", initial="", max_width=16, label="Robinsons Limit", column_label="Rob.Limit", position=112, order=1460, help="Robinsons limit")
        t.column('MobileNumber', 'character', format="x(16)", initial="", help="Mobile contact number", max_width=32, label="Mobile Contact Number", column_label="Mob.Nbr", position=113, order=1470, description='''
''')
        t.column('Birthday', 'date', format="99-99-99", help="Birthday", max_width=4, label="Birthday", position=114, order=1480, description='''
''')
        t.column('CompanyName', 'character', format="x(30)", initial="", max_width=60, label="Company Name", column_label="Company", position=115, order=1490, help="Company name")
        t.column('AddressCodC', 'character', format="X(8)", initial="", max_width=16, label="Address CodC", column_label="CodC", position=116, order=1500, help="CodC in address validation")
        t.column('AddressCodP', 'character', format="X(8)", initial="", max_width=16, label="Address CodP", column_label="CodP", position=117, order=1510, help="CodP in address validation")
        t.column('FoundationDate', 'date', format="99-99-99", max_width=4, label="Foundation Date", column_label="Found.Date", position=118, order=1520)
        t.column('ExtInvRef', 'character', format="X(50)", initial="", help="External Invoice Reference", max_width=100, label="External InvRef", column_label="ExtInvRef", position=119, order=1530, description="External invoice reference for corporate customers")
        t.column('DataProtected', 'logical', format="Yes/No", initial="No", max_width=1, label="Data Protected", column_label="DataProtected", position=120, order=1540, help="Is the data protection required by customer")
        t.column('Profession', 'character', format="x(8)", initial="", max_width=16, label="Profession", column_label="Profession", position=121, order=1550)
        t.column('OutMarkBank', 'logical', format="Yes/No", initial="No", max_width=1, label="OutMarkBank", column_label="OutMarkBank", position=122, order=1560, help="3rd Party Bank Marketing")
        t.column('AuthCustIdType', 'character', format="x(8)", initial="", max_width=16, label="AuthCustIdType", column_label="AuthCustIdType", position=123, order=1570, help="Authorization Cistomer ID Type")
        t.column('AuthCustId', 'character', format="x(11)", initial="", max_width=22, label="AuthCustId", column_label="AuthCustId", position=124, order=1580, help="Authorization Customer ID")
        t.index('CustNum_s', [['CustNum']], area="Sta_Index_1_2", primary=True, unique=True)
        t.index('AgrCust', [['AgrCust']], area="Sta_Index_1_2")
        t.index('BankAcct', [['Brand'], ['BankAcct']], area="Sta_Index_1_2")
        t.index('CompanyName', [['Brand'], ['CompanyName']], area="Sta_Index_1_2")
        t.index('CustName', [['Brand'], ['CustName'], ['FirstName']], area="Sta_Index_1_2")
        t.index('CustNum', [['Brand'], ['CustNum']], area="Sta_Index_1_2")
        t.index('FirstName', [['Brand'], ['FirstName']], area="Sta_Index_1_2")
        t.index('InvCode', [['Brand'], ['InvCode'], ['CustNum']], area="Sta_Index_1_2")
        t.index('InvCust', [['InvCust']], area="Sta_Index_1_2")
        t.index('InvGroup', [['Brand'], ['InvGroup'], ['CustNum']], area="Sta_Index_1_2")
        t.index('Orgid', [['Brand'], ['OrgId']], area="Sta_Index_1_2")
        t.index('RateCust', [['RateCust']], area="Sta_Index_1_2")
        t.index('RepCust', [['RepCust']], area="Sta_Index_1_2")
        t.index('SearchName', [['Brand'], ['SearchName'], ['CustName']], area="Sta_Index_1_2")
        t.index('SurName2', [['Brand'], ['SurName2'], ['CustName'], ['FirstName']], area="Sta_Index_1_2")
        t.index('ZipCode', [['Brand'], ['ZipCode'], ['CustNum']], area="Sta_Index_1_2")

    def down(self):
        self.drop_table('Customer')
