from gearbox.migrations import Migration

class AddTableOrder(Migration):

    database = "ordercanal"

    def up(self):
        t = self.table('Order', area="Sta_Data_32", table_trigger=[{'crc': '?', 'procedure': 'rd-order.p', 'override_proc': True, 'event': 'REPLICATION-DELETE'}, {'crc': '?', 'procedure': 'rw-order.p', 'override_proc': True, 'event': 'REPLICATION-WRITE'}], dump_name="order")
        t.column('OrderId', 'integer', mandatory=True, format=">>>>>>>>9", initial="0", max_width=4, label="OrderId", column_label="OrderId", position=2, order=10, description="Order sequence number")
        t.column('CustNum', 'integer', format=">>>>>>>>9", initial="0", help="Reference customer number", max_width=4, label="CustNum", column_label="CustNum", position=3, order=20, description="Reference customer number")
        t.column('Source', 'character', format="x(8)", initial="", help="Source of order", max_width=16, label="Source", column_label="Source", position=9, order=90, description="Source of order")
        t.column('CLI', 'character', format="x(11)", initial="", max_width=22, label="MSISDN", column_label="MSISDN No", position=10, order=100, help="MSISDN Subscriber No")
        t.column('CLIType', 'character', format="x(8)", initial="", help="CLI Type", max_width=16, label="CLIType", column_label="CLIType", position=11, order=110, description="CLI Type")
        t.column('CredOK', 'logical', format="yes/no", initial="no", max_width=1, label="Credit", column_label="Credit", position=12, order=130, help="Is the customers credit ok?")
        t.column('StatusCode', 'character', format="x(8)", initial="", help="Status of order", max_width=16, label="Status", column_label="Status", position=13, order=140, description="Status of order")
        t.column('CrStamp', 'decimal', format="99999999.99999", decimals=5, initial="0", help="When was the order created", max_width=20, label="Created", column_label="Created", position=14, order=150, description="Create timestamp")
        t.column('ContactNum', 'character', format="x(12)", initial="", max_width=24, label="ContactNum", column_label="ContactNum", position=19, order=180, description="Contact Phone number")
        t.column('MNPStatus', 'integer', format="99", initial="0", max_width=4, label="MNPStatus", column_label="MNPStatus", position=26, order=240, help="Status of MNP")
        t.column('MNPNumber', 'character', format="x(12)", initial="", max_width=24, label="MNP Number", column_label="MNP Number", position=27, order=260, help="MNP Number")
        t.column('CurrOper', 'character', format="x(15)", initial="", max_width=30, label="Current Operator", column_label="Current Operator", position=28, order=250, help="Current Operator")
        t.column('Salesman', 'character', format="x(8)", initial="", max_width=16, label="Salesman", column_label="Salesman", position=29, order=270, help="Code of that salesman who is responsible of this reseller")
        t.column('Brand', 'character', format="x(8)", initial="", max_width=16, label="Brand", column_label="Brand", position=30, order=290, help="Code Of Brand")
        t.column('Tupas', 'integer', format=">9", initial="0", max_width=4, label="Tupas", column_label="Tupas", position=31, order=280)
        t.column('TupasRM', 'character', format="x(200)", initial="", help="Tupas Return Message", max_width=400, label="TupasRM", column_label="TupasRM", position=32, order=300, description="Tupas Return Message")
        t.column('TempCLI', 'character', format="x(11)", initial="", max_width=22, label="Temp MSISDN", column_label="Temp MSISDN", position=39, order=880, help="Temporary MSISDN Subscriber No")
        t.column('InvCustRole', 'integer', format="9", initial="1", help="Invoice customer role", max_width=4, label="Inv.Customer Role", column_label="ICRole", position=40, order=890, description='''


''')
        t.column('UserRole', 'integer', format="9", initial="1", help="User customer role", max_width=4, label="User Customer Role", column_label="UserRole", position=41, order=900, description='''
''')
        t.column('Reseller', 'character', format="x(8)", initial="", max_width=16, label="Reseller", column_label="Resell", position=42, order=910, help="Reseller code")
        t.column('OrdererIP', 'character', format="x(20)", initial="", max_width=40, label="Orderer IP", column_label="Ord.IP", position=43, order=920, help="Orderer IP")
        t.column('ResellerMobNbr', 'character', format="x(14)", initial="", max_width=28, label="Reseller Mobile Number", column_label="Res.Mobile", position=44, order=930, help="Reseller mobile number")
        t.column('OldPayType', 'logical', format="PrePaid/PostPaid", initial="no", max_width=1, label="Old Pay Type", column_label="Old PT", position=45, order=940, help="Old pay type")
        t.column('Orderer', 'character', format="x(30)", initial="", max_width=60, label="Orderer", position=46, order=950, help="Orderer")
        t.column('OrdererIDType', 'character', format="x(8)", initial="", max_width=16, label="Orderer ID Type", column_label="Ord.IDType", position=47, order=960, help="Orderer ID type")
        t.column('OrdererID', 'character', format="x(10)", initial="", max_width=20, label="Orderer ID", column_label="Ord.ID", position=48, order=970, help="Orderer ID")
        t.column('CREventQty', 'integer', format=">>9", initial="0", max_width=4, label="Credit Event Qty", column_label="CREvent Qty", position=49, order=480, help="Credit event quantity")
        t.column('DepoFeeAmt', 'decimal', format="->>>>>9.99", decimals=2, initial="0", max_width=17, label="Deposit Fee Amount", column_label="DepoFee", position=50, order=490, help="Deposit fee amount")
        t.column('Foreign', 'logical', format="Yes/No", initial="no", max_width=1, label="Foreign", position=51, order=500, help="Foreign user")
        t.column('InhabitClass', 'integer', format="9", initial="0", max_width=4, label="Inhabit Class", column_label="Inhabit", position=52, order=510, help="Inhabit class")
        t.column('CreditRate', 'character', format="x(8)", initial="", max_width=16, label="Credit Rating", column_label="CrRate", position=53, order=470, help="Credit rating class")
        t.column('ClaimState', 'integer', format=">9", initial="0", max_width=4, label="In Claiming", column_label="Claimed", position=54, order=520, help="Customer has invoices in claiming process")
        t.column('PNPNumbers', 'character', format="x(50)", initial="", max_width=100, label="PNP Numbers", column_label="PNP", position=55, order=530, help="PNP numbers")
        t.column('OrderType', 'integer', format="9", initial="0", max_width=4, label="Type", column_label="Type", position=57, order=550, help="Order type")
        t.column('SendToROI', 'integer', format="9", initial="0", max_width=4, label="Send History to ROI", position=58, order=1060)
        t.column('RiskCode', 'character', format="x(10)", initial="", max_width=20, label="ROI Risk Code", position=59, order=1070)
        t.column('UsageType', 'character', format="x(8)", initial="", max_width=16, label="Usage Type", column_label="UsageType", position=60, order=1100)
        t.column('LeadNbr', 'integer', format=">>>>>>>9", initial="0", max_width=4, label="Lead Number", column_label="Lead", position=61, order=600, help="Lead number")
        t.column('ICC', 'character', format="x(20)", initial="", help="SIM card serial no.", max_width=40, label="ICC", column_label="ICC", position=62, order=580, description="SIM card serial no.")
        t.column('OrderChannel', 'character', format="x(16)", initial="", max_width=32, label="Order Channel", column_label="Channel", position=63, order=610, help="Order channel")
        t.column('MSSeq', 'integer', format=">>>>>>>9", initial="0", max_width=4, label="MobSub Sequence", column_label="MobSub", position=64, order=620, help="Link to MobSub")
        t.column('Campaign', 'character', format="x(8)", initial="", max_width=16, label="Campaign ID", column_label="ID", position=65, order=630, help="Campaign ID")
        t.column('Referee', 'character', format="x(16)", initial="", max_width=32, label="Referee", column_label="Ref", position=66, order=650, help="Referee's CLI")
        t.column('PortingTime', 'decimal', format="99.99", decimals=2, initial="0", max_width=17, label="PortingTime", column_label="PortingTime", position=67, order=660, help="PortingTime")
        t.column('FeeModel', 'character', format="x(8)", initial="", max_width=16, label="BEvent", column_label="FeeModel", position=68, order=670, help="An unique code for a Billing Event")
        t.column('PortingDate', 'date', format="99-99-99", max_width=4, label="PortingDate", column_label="PortingDate", position=69, order=640, help="Porting date")
        t.column('PayType', 'logical', format="PrePaid/PostPaid", initial="no", help="PayType", max_width=1, label="PayType", column_label="PayType", position=87, order=840, description='''

''')
        t.column('OldIcc', 'character', format="x(20)", initial="", max_width=40, label="Old ICC", column_label="Old ICC", position=88, order=850)
        t.column('DeviceID', 'character', format="x(16)", initial="", help="DeviceID", max_width=32, label="DeviceID", column_label="DeviceID", position=89, order=860, description='''


''')
        t.column('InvNum', 'integer', format=">>>>>>>9", initial="0", max_width=4, label="Invoice Nbr", column_label="InvNum", position=90, order=980, help="Invoice number")
        t.column('ContractID', 'character', format="x(12)", initial="", max_width=24, label="Contract ID", column_label="ContrID", position=91, order=990, help="Contract ID")
        t.column('FATAmount', 'decimal', format="->>>>>>9.99", decimals=2, initial="0", max_width=17, label="FAT Amount", column_label="FAT", position=92, order=1000, help="FATime amount")
        t.column('SMSType', 'integer', format=">9", initial="0", max_width=3, label="SMS Type", column_label="SMS Type", position=93, order=1010, help="SMS Type")
        t.column('Offer', 'character', format="x(12)", initial="", max_width=24, label="Offer ID", column_label="Offer", position=94, order=1020, help="Offer ID")
        t.column('Logistics', 'character', format="x(30)", initial="", max_width=60, label="Logistics", column_label="Logistics", position=95, order=1030, help="Logistics file name")
        t.column('FtGrp', 'character', format="x(8)", initial="", max_width=16, label="FATime Group", column_label="FATGroup", position=96, order=1040, help="FATime group")
        t.column('ROIResult', 'character', format="x(20)", initial="", max_width=40, label="ROI Result", column_label="ROI", position=97, order=1050, help="Result code from ROI")
        t.column('MultiSimID', 'integer', format=">>>>>>>9", initial="0", max_width=4, label="Multi SIM ID", column_label="MultiSimID", position=98, order=1080, help="Multi SIM ID")
        t.column('MultiSimType', 'integer', format=">>>9", initial="0", max_width=4, label="Multi SIM Type", column_label="MultiSimType", position=99, order=1090, help="Multi SIM type (1=primary, 2=secondary)")
        t.column('DeliveryType', 'integer', format=">>9", initial="0", max_width=4, label="Delivery Type", column_label="DeliveryType", position=100, order=1120)
        t.column('DeliverySecure', 'integer', format=">9", initial="0", max_width=4, label="DeliverySecure", column_label="DeliverySecure", position=101, order=1130)
        t.column('CampaignType', 'character', format="x(12)", initial="", max_width=24, label="Campaign Type", column_label="CampaignType", position=102, order=1110)
        t.column('SendOffer', 'logical', format="yes/no", initial="no", max_width=1, label="Send Offer", column_label="SendOffer", position=103, order=1140)
        t.column('ResignationPeriod', 'logical', format="yes/no", initial="no", max_width=1, label="Resignation Period", column_label="ResignationPeriod", position=104, order=1150)
        t.column('RoiLevel', 'integer', format=">9", initial="0", max_width=4, label="ROI Level", column_label="ROILevel", position=105, order=1160)
        t.column('Multiorder', 'logical', format="Yes/No", initial="No", max_width=1, label="Multiorder", column_label="Multiorder", position=106, order=1170)
        t.index('OrderID', [['Brand'], ['OrderId']], area="Sta_Index_1", primary=True, unique=True)
        t.index('CLI', [['Brand'], ['CLI'], ['CrStamp', 'DESC'], ['OrderType'], ['Tupas']], area="Sta_Index_1")
        t.index('CLI_s', [['CLI'], ['CrStamp', 'DESC']], area="Sta_Index_1")
        t.index('ContractID', [['Brand'], ['ContractID']], area="Sta_Index_1")
        t.index('CustNum', [['Brand'], ['CustNum'], ['CrStamp', 'DESC']], area="Sta_Index_1")
        t.index('CustNum_s', [['CustNum'], ['CrStamp', 'DESC']], area="Sta_Index_1")
        t.index('InvNum', [['InvNum']], area="Sta_Index_1")
        t.index('MSSeq', [['MSSeq']], area="Sta_Index_1")
        t.index('MultiSimID', [['Brand'], ['MultiSimID', 'DESC']], area="Dyn_Index_1")
        t.index('OrderIDBr', [['Brand'], ['OrderId'], ['OrderType'], ['Tupas']], area="Sta_Index_1")
        t.index('Salesman', [['Brand'], ['Salesman'], ['StatusCode']], area="Dyn_Index_1")
        t.index('SendToROI', [['Brand'], ['SendToROI']], area="Sta_Index_1")
        t.index('Source', [['Brand'], ['Source'], ['CrStamp', 'DESC']], area="Sta_Index_1")
        t.index('Stamp', [['Brand'], ['CrStamp', 'DESC'], ['OrderType'], ['Tupas']], area="Sta_Index_1")
        t.index('StatusCLI', [['Brand'], ['StatusCode'], ['CLI']], area="Sta_Index_1")
        t.index('StatusCode', [['Brand'], ['StatusCode'], ['CrStamp', 'DESC']], area="Sta_Index_1")
        t.index('StContractID', [['Brand'], ['StatusCode'], ['ContractID']], area="Sta_Index_1")
        t.index('StOrderID', [['Brand'], ['StatusCode'], ['OrderId']], area="Sta_Index_1")

    def down(self):
        self.drop_table('Order')
