from gearbox.migrations import Migration

class AddTableOrderCustomer(Migration):

    database = "ordercanal"

    def up(self):
        t = self.table('OrderCustomer', area="Sta_Data_32", table_trigger=[{'crc': '?', 'procedure': 'rd-ordercustomer.p', 'override_proc': True, 'event': 'REPLICATION-DELETE'}, {'crc': '?', 'procedure': 'rw-ordercustomer.p', 'override_proc': True, 'event': 'REPLICATION-WRITE'}], dump_name="ordercus")
        t.column('RowType', 'integer', format=">>9", initial="0", max_width=4, label="RowType", column_label="RowType", position=2, order=10, help="Order customer type")
        t.column('Address', 'character', format="x(30)", initial="", max_width=60, label="Address", column_label="Address", position=3, order=50, help="Customer's mailing address (street, p.o. box)")
        t.column('BirthDay', 'date', format="99.99.99", initial=self.unknown, max_width=4, label="BirthDay", column_label="BirthDay", position=4, order=100)
        t.column('ContactNum', 'character', format="x(12)", initial="", max_width=24, label="ContactNum", column_label="ContactNum", position=5, order=80, description="Contact Phone number")
        t.column('Country', 'character', format="x(2)", initial="", max_width=4, label="Country", position=6, order=120, help="Agreement customer's country")
        t.column('CustNum', 'integer', format=">>>>>>>>9", initial="0", help="Reference customer number", max_width=4, label="CustNum", column_label="CustNum", position=7, order=20, description="Reference customer number")
        t.column('Email', 'character', format="x(60)", initial="", max_width=120, label="Email", column_label="Email", position=8, order=90, help="Customer's Email ID")
        t.column('FirstName', 'character', format="x(20)", initial="", help="Customer's fore/given name", max_width=40, label="ForeName", column_label="ForeName", position=9, order=30, description="Customer's forename")
        t.column('SurName1', 'character', format="x(20)", initial="", help="Customer's 1st last name", max_width=40, label="SurName1", column_label="SurName1", position=10, order=40, description="Customer's 1st last name")
        t.column('OrderId', 'integer', mandatory=True, format=">>>>>>>>9", initial="0", max_width=4, label="OrderId", column_label="OrderId", position=11, order=130, description="Order sequence number")
        t.column('Sex', 'character', format="X(8)", initial="", max_width=16, label="Sex", position=12, order=110)
        t.column('ZipCode', 'character', format="x(8)", initial="", max_width=16, label="Postal code", column_label="Postcd", position=13, order=60, help="Customer's postal code")
        t.column('PostOffice', 'character', format="x(24)", initial="", max_width=48, label="Postal Addr.", column_label="Postaddr", position=14, order=70, help="Customer's postal address")
        t.column('SurName2', 'character', format="x(20)", initial="", help="Customer's 2nd last name", max_width=40, label="SurName2", column_label="SurName2", position=15, order=140, description="Customer's 2nd last name")
        t.column('CustId', 'character', format="x(12)", initial="", max_width=24, label="CustId", column_label="CustId", position=16, order=150)
        t.column('CustIdType', 'character', format="x(8)", initial="", max_width=16, label="CustIdType", column_label="CustIdType", position=17, order=160)
        t.column('Company', 'character', format="x(20)", initial="", help="Company name", max_width=40, label="Company", column_label="Company", position=18, order=170, description="Company name")
        t.column('Nationality', 'character', format="x(2)", initial="", max_width=4, label="Nationality", column_label="Nationality", position=19, order=180)
        t.column('Region', 'character', format="x(12)", initial="", max_width=24, label="Region", column_label="Region", position=20, order=190)
        t.column('MobileNumber', 'character', format="x(10)", initial="", max_width=20, label="MobileNumber", column_label="MobileNumber", position=21, order=200)
        t.column('FixedNumber', 'character', format="x(10)", initial="", max_width=20, label="FixedNumber", column_label="FixedNumber", position=22, order=210)
        t.column('Language', 'character', format="x(2)", initial="", max_width=4, label="Language", column_label="Language", position=23, order=220)
        t.column('OperSMSMarketing', 'logical', format="Yes/No", initial="no", max_width=1, label="OperSMSMarketing", column_label="OperSMSMarketing", position=24, order=230)
        t.column('OperEMailMarketing', 'logical', format="Yes/No", initial="no", max_width=1, label="OperEMailMarketing", column_label="OperEMailMarketing", position=25, order=240)
        t.column('OperPostMarketing', 'logical', format="Yes/No", initial="no", max_width=1, label="OperPostMarketing", column_label="OperPostMarketing", position=26, order=250)
        t.column('OutEMailMarketing', 'logical', format="Yes/No", initial="no", max_width=1, label="OutEMailMarketing", column_label="OutEMailMarketing", position=27, order=260)
        t.column('OutPostMarketing', 'logical', format="Yes/No", initial="no", max_width=1, label="OutPostMarketing", column_label="OutPostMarketing", position=28, order=270)
        t.column('OutSMSMarketing', 'logical', format="Yes/No", initial="no", max_width=1, label="OutSMSMarketing", column_label="OutSMSMarketing", position=29, order=280)
        t.column('OperAllMarketing', 'logical', format="Yes/No", initial="no", max_width=1, label="OperAllMarketing", column_label="OperAllMarketing", position=30, order=290)
        t.column('Brand', 'character', format="x(8)", initial="", max_width=16, label="Brand", column_label="Brand", position=31, order=300, help="Code Of Brand")
        t.column('Category', 'character', format="x(4)", initial="", max_width=8, label="Category", column_label="Cat.", position=32, order=740, help="Category code of agreement customer")
        t.column('PersonId', 'character', format="x(11)", initial="", help="Personal Number", max_width=22, label="PersonId", column_label="PersonId", position=33, order=750, description="Personal Number")
        t.column('CustTitle', 'character', format="x(12)", initial="", max_width=24, label="Title", column_label="Title", position=34, order=760)
        t.column('BankCode', 'character', format="x(10)", initial="", max_width=20, label="BankCode", column_label="BankCode", position=35, order=770)
        t.column('CustUserId', 'character', format="x(8)", initial="", max_width=16, label="UserId", column_label="UserId", position=36, order=780)
        t.column('CustPWD', 'character', format="x(8)", initial="", max_width=16, label="Password", column_label="Password", position=37, order=790)
        t.column('VatPercent', 'decimal', format=">9.99", decimals=2, initial="0", max_width=17, label="Vat%", column_label="Vat%", position=38, order=800)
        t.column('VatCode', 'character', format="x(4)", initial="", max_width=6, label="VatCode", column_label="VatCode", position=39, order=810)
        t.column('Passport', 'character', format="x(12)", initial="", max_width=24, label="Passport", column_label="Passport", position=40, order=820)
        t.column('AddressCodC', 'character', format="X(8)", initial="", max_width=16, label="Address CodC", column_label="CodC", position=41, order=830, help="CodC in address validation")
        t.column('AddressCodP', 'character', format="X(8)", initial="", max_width=16, label="Address CodP", column_label="CodP", position=42, order=840, help="CodP in address validation")
        t.column('SelfEmployed', 'logical', format="yes/no", initial="no", max_width=1, label="Selfemployed", column_label="Selfempl.", position=43, order=850)
        t.column('FoundationDate', 'date', format="99-99-99", initial=self.unknown, max_width=4, label="Foundation Date", column_label="Found.Date", position=44, order=860)
        t.column('ExtInvRef', 'character', format="X(50)", initial="", help="External Invoice Reference", max_width=100, label="External InvRef", column_label="ExtInvRef", position=45, order=870, description="External invoice reference for corporate customers")
        t.column('SubQty', 'integer', format=">>>>9", initial="0", help="Max subscription quantity", max_width=4, label="SubQty", column_label="SubQty", position=46, order=880, description="Max subscription quantity for customer")
        t.column('DataChecked', 'logical', format="Yes/No", initial="No", help="Is the data checked", max_width=1, label="DataChecked", column_label="DataChecked", position=47, order=890, description="Is the ordercustomer data checked")
        t.column('Street', 'character', format="x(30)", initial="", max_width=60, label="Street", column_label="Street", position=51, order=900)
        t.column('BuildingNum', 'character', format="x(8)", initial="", max_width=16, label="Building Number", column_label="Building Number", position=52, order=910)
        t.column('AddressCompl', 'character', format="x(20)", initial="", max_width=40, label="Address Complement", column_label="Address Complement", position=53, order=920)
        t.column('AdditionalDoc', 'integer', format=">9", initial="0", max_width=4, label="Additional Documentation", column_label="Additional Documentation", position=54, order=930)
        t.column('DelType', 'integer', format=">9", initial=self.unknown, max_width=4, label="Inv Delivery Type", column_label="Inv Delivery Type", position=55, order=940)
        t.column('AddressCodM', 'character', format="X(8)", initial="", max_width=16, label="Address CodM", column_label="CodM", position=56, order=950, help="CodM in address validation")
        t.column('Latitude', 'character', format="X(14)", initial="", max_width=28, label="Latitude", column_label="Latitude", position=57, order=960, help="Latitude in address validation")
        t.column('Longitude', 'character', format="X(14)", initial="", max_width=28, label="Longitude", column_label="Longitude", position=58, order=970, help="Longitude in address validation")
        t.column('Profession', 'character', format="x(8)", initial="", max_width=16, label="Profession", column_label="Profession", position=59, order=980)
        t.column('KialaCode', 'character', format="x(5)", initial="", max_width=10, label="Kiala Code", column_label="KialaCode", position=60, order=1000)
        t.column('OutBankMarketing', 'logical', format="Yes/No", initial="No", max_width=1, label="OutBankMarketing", column_label="OutBankMarketing", position=61, order=990, help="3rd Party Bank Marketing")
        t.column('CustDataRetr', 'logical', format="Yes/No", initial="No", max_width=1, label="Customer data Retrieved", column_label="CustDataRetr", position=62, order=1010)
        t.column('MSISDNForIdent', 'character', format="x(12)", initial="", max_width=24, label="MSISDN For Identification", column_label="MSISDNForIdent", position=63, order=1020)
        t.index('OrderId', [['Brand'], ['OrderId'], ['RowType']], area="Sta_Index_1", primary=True)
        t.index('CustID', [['Brand'], ['CustIdType'], ['CustId']], area="Sta_Index_1")
        t.index('CustNum', [['CustNum'], ['RowType'], ['OrderId']], area="Sta_Index_1")

    def down(self):
        self.drop_table('OrderCustomer')
