DEFINE INPUT PARAMETER pcInputFile AS CHARACTER NO-UNDO. 
DEFINE INPUT PARAMETER pcOutputFile AS CHARACTER NO-UNDO. 
DEFINE VARIABLE cLine AS CHARACTER NO-UNDO. 

DEFINE STREAM sin.
DEFINE STREAM sout.

INPUT STREAM sin FROM VALUE(pcInputFile).
OUTPUT STREAM sout TO VALUE(pcOutputFile).

REPEAT:
   IMPORT STREAM sin UNFORMATTED cLine.
   cLine = TRIM(cLine).
   PUT STREAM sout UNFORMATTED cLine SKIP.
END.

OUTPUT STREAM sout CLOSE.
INPUT STREAM sin CLOSE.

