DEFINE VARIABLE cFile AS CHARACTER NO-UNDO. 
cFile = "/apps/snet/200901/hm_ycm1240.output".

DEFINE STREAM sICC.
OUTPUT STREAM sICC TO VALUE(cFile).

FOR EACH SIM WHERE 
    SIM.Brand = "1" AND SIM.Stock = "CC" AND 
    SIM.SimStat = 1 NO-LOCK:

    PUT STREAM sICC UNFORMATTED SIM.ICC SKIP.
END.
OUTPUT STREAM sICC CLOSE.


