#!/bin/bash
#
# This daemon polls the common.replog table and sends one HPD message
# for each record of the table.
#

DAEMON=HPD.HPDOnline
INSTANCE=Common
LOGLEVEL=4
DATABASES="common ordercanal mobile"
cd $(dirname $0)/..
. script/daemon.sh
