TRIGGER PROCEDURE FOR REPLICATION-DELETE OF MSISDN.

FIND MSISDN_new EXCLUSIVE-LOCK WHERE
     MSISDN_new.Brand = MSISDN.Brand AND
     MSISDN_new.CLI = MSISDN.CLI AND
     MSISDN_new.ValidFrom = MSISDN.ValidFrom NO-ERROR.
IF AVAIL MSISDN_new THEN DELETE MSISDN_new.
